const Page = () => {
  return (
    <main className="">
      <div>Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard Dashboard </div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
    </main>
  );
};

export default Page;
