import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { ViewTransitions } from 'next-view-transitions';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['700', '600', '400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${poppins.className} bg-neutral-00 font-normal`}>{children}</body>
      </html>
    </ViewTransitions>
  );
}
